version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
      - 9600:9600
      - 9600:9600/udp 
      - 50041:50041 
      - 50042:50042 
    volumes:
      - type: bind
        source: "./assetto/cfg"
        target: "/assetto/cfg"
      - type: bind
        source: "./assetto/content"
        target: "/assetto/content"
